typography_spectrum: 0.145833
color:
  brandColors:
    - '#C0B8A8'
    - '#284878'
    - '#687088'
    - '#60A0C0'
    - '#000000'
  brandStrength: 0.6331490473821759
  lightness: 0.5310865149367601
  rhythmicContrast: 0.961644463473931
  saturation: 0.6407220088876784
opengraph: {}
layout_spectrum: 0.896929
analytics: {}
author:
  email: orangebird4@yahoo.com
  name: thompson alexander bishop
  url: thompsonalexanderbishop.com
name: the quiet we live by
cta: {}
title: red wind that once
description: poetics of thompson alexander bishop
purpose: []
