name: the quiet we live by
favicon: null
layout_spectrum: 0.9504820839501917
typography_spectrum: 0.050755035132169724
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6331490473821759
  lightness: 0.5310865149367601
  saturation: 0.6407220088876784
  rhythmicContrast: 0.961644463473931
purpose: []
